dev
size12/gophermart pull request #1
Opened 2023-01-25 11:30 UTC by size12

2023-01-27 07:35 UTC, size12 commented
что-то максимальный костыль сделал для регистрации, надо подумать как лучше сделать, пока что мыслей нет годных.

2023-01-29 17:41 UTC, size12 commented
сделал новый тип кук, в которых хранится ID пользователя.

2023-01-29 18:27 UTC, size12 commented
Прикрепляю видос, объясняющий мой "волшебный" код. Никакие библиотеки я не менял, да и зачем?
`sign := append([]byte{cookie[8]}, cookie[9:40]...)`

2023-02-02 18:13 UTC, size12 commented
переделал логику вывода, теперь баланс проверяется и обновляется одним запросом.

2023-02-07 14:37 UTC, size12 commented
fan-out & fan-in не получилось сделать, чтобы проходило тесты(локально работало всё нормально). Сделал чисто. fan-out, каждая горутина сама вызывает добавление результата в хранилище.

2023-02-13 07:47 UTC, Bazys requested changes

2023-02-13 07:47 UTC, Bazys commented on accrualsystem/accrual_system.go
> +package accrualsystem
а почему это в отдельном каталоге?

2023-02-13 07:47 UTC, Bazys commented on internal/storage/queue.go
> +	PushFrontOrders(orders ...entity.Order) error
почему так?
с одним параметром это не имеет смысла!

2023-02-13 07:47 UTC, Bazys commented on internal/storage/queue.go
> +	*sync.Mutex
а может использовать RWMutex?

2023-02-13 07:47 UTC, Bazys commented on internal/storage/errors.go
> +var ErrNotFound = errors.New("not found")
множественное объявление ?

2023-02-13 07:47 UTC, Bazys commented on internal/storage/db_storage.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
1 секунда?
и может в константу или в конфиг

2023-02-13 07:47 UTC, Bazys commented on internal/storage/db_storage.go
> +	rows, err := s.DB.QueryContext(ctx, `SELECT userid, num, stat FROM orders WHERE stat = 'NEW' OR stat = 'PROCESSING' ORDER BY uploaded ASC `)
каждый раз выбирать все заказы в этом статусе слишком.
Надо как то ограничивать.

2023-02-13 07:47 UTC, Bazys commented on internal/storage/db_storage.go
> +	_, err = DB.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS users (id INT GENERATED BY DEFAULT AS IDENTITY, login VARCHAR(255), passw VARCHAR(255), balance FLOAT, withdrawn FLOAT)`)
ты взрослый мальчик!
почему не используешь мигратор?

2023-02-13 07:47 UTC, Bazys commented on internal/storage/db_storage.go
> +	case "id":
а если случайно ни то ни другое?
плохая практика передавать просто строку.
создай enum

2023-02-13 07:47 UTC, Bazys commented on internal/storage/db_storage.go
> +	hash := hex.EncodeToString(h.Sum(nil))
а использовать стандартные методы работы с паролем?
bcrypt.GenerateFromPassword
bcrypt.CompareHashAndPassword

2023-02-13 07:47 UTC, Bazys commented on internal/middleware/authentication.go
> +			if path == "/api/user/register" || path == "/api/user/login" {
а вместо таких плясок, может просто вешать эту мидлеварь на нужную группу роутов?

2023-02-13 07:47 UTC, Bazys commented on internal/storage/db_storage.go
> +		} else {
зачем это else?

2023-02-13 07:47 UTC, Bazys commented on internal/storage/storage.go
> +		b[i] = letters[rand.Intn(len(letters))]
ты большой мальчик, может лучше использовать взрослые функции - crypto/rand

2023-02-13 07:47 UTC, Bazys commented on accrualsystem/external_accrual_system.go
> +	url := fmt.Sprintf("%s%s%v", s.BaseURL, path, order.Number)
почему %v?
ты же точно знаешь что `order.Number` это целое число.
Но в принципе для этих целей целый пакет есть - https://pkg.go.dev/net/url

2023-02-13 07:47 UTC, Bazys commented on internal/storage/db_storage.go
> +func (s *DBStorage) PushBackOrders(orders ...entity.Order) error {
а зачем возвращать ошибку, если ты её ни разу не проверяешь?

2023-02-13 07:47 UTC, Bazys commented on internal/storage/db_storage.go
> +func (s *DBStorage) UpdateOrders(ctx context.Context, orders ...entity.Order) error {
а зачем возвращать ошибку, если ты её ни разу не проверяешь?

2023-02-13 07:47 UTC, Bazys commented on internal/handlers/withdraw/withdraw.go
> +		user := r.Context().Value(entity.CtxUserKey{}).(entity.User)
а вдруг там лежит что то совершенно другое, а ты даже не проверил.

2023-02-13 07:47 UTC, Bazys commented on internal/config/config.go
> +	env.Parse(&cfg)
а если не смогли распарсить? ты об этом даже не узнаешь.
и будешь гадать почему твоё приложение не к тому серверу конектится.

2023-02-13 12:05 UTC, size12 commented on internal/storage/queue.go
> +	PushFrontOrders(orders ...entity.Order) error
потому что при запуске DB в очередь добавляются необработанные ордера, и чтобы по одному их в очередь не добавлять, делаю так

2023-02-14 23:08 UTC, Bazys commented on internal/storage/queue.go
> +	PushFrontOrders(orders ...entity.Order) error
чем просто слайс не устаривает, в качестве параметра?

2023-02-15 04:58 UTC, size12 commented on internal/storage/queue.go
> +	PushFrontOrders(orders ...entity.Order) error
кажется понял в чём косяк...  
сделал так: если в конец очереди, то только 1 можно добавить, если в начало, то добавляю слайсом.

2023-02-17 07:02 UTC, Bazys requested changes
Добавить контроль горутин. Почитай вот это:
1. https://medium.com/german-gorelkin/data-protected-by-confinement-ec6b7be401ea
2. https://itnext.io/explain-to-me-go-concurrency-worker-pool-pattern-like-im-five-e5f1be71e2b0

2023-02-17 07:02 UTC, Bazys commented on internal/handlers/withdraw/withdraw.go
> +func WithdrawHandler(s storage.Storage) http.HandlerFunc {
withdraw.WithdrawHandler -  масло масляное.
может проще быть? withdraw.Handler

2023-02-17 07:02 UTC, Bazys commented on internal/handlers/withdraw/withdraw.go
> +		user := value.(entity.User)
если в value лежит совсем не user то ты получишь панику в рантайме.
Приучайся обрабатывать assertion через ok

2023-02-17 07:02 UTC, Bazys commented on internal/storage/storage.go
> +var letters = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
для чего это?

2023-02-17 07:02 UTC, Bazys commented on internal/storage/db_storage.go
> +func MigrateUP(DB *sql.DB) error {
параметры не надо в аппер-кейсе делать, за исключением случаев типа URI и т.д., что в гошечке зафиксировано

2023-02-17 07:02 UTC, Bazys commented on internal/handlers/orders/order.go
> +func OrderHandler(s storage.Storage) http.HandlerFunc {
здесь тоже масло масляное

2023-02-17 07:02 UTC, Bazys commented on internal/app/accrual.go
> +	go func() {
абсолютно неуправляемая горутина. Ни контекста ни спец канала для остановки.

2023-02-17 07:02 UTC, Bazys commented on internal/app/accrual.go
> +		pool.StartWorker()
Порождаем хренову тучу горутин и никак их не контролируем!

2023-02-18 13:11 UTC, Bazys approved these changes

2023-02-18 13:19 UTC, merged